### ISSUE TITLE
remove the backend folder

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#10]
Remove the backend folder from the project making sure that the project doesn't give errors. Remove any part from the frontend where its linked to the backend folder.

**Comment by ArchismanKarmakar** [comment]
I want to take up this issue please assign me

**Comment by mohit200008** [comment]
Sure @ArchismanKarmakar  go ahead

**Comment by ArchismanKarmakar** [comment]
> Sure @ArchismanKarmakar go ahead

Done sir, though I have not removed the backend folder from the forked repo but you can check it's definitely not in use
![1](https://user-images.githubusercontent.com/92569441/144854237-003c2f23-5b2d-422e-ad5d-d972e5110a22.png)

https://user-images.githubusercontent.com/92569441/144855862-0c9b8102-4327-4bae-b026-350618f45d21.mp4

.

**Comment by mohit200008** [comment]
remove the backend folder from the project and make sure the project  doesn't give any  errors

**Comment by ArchismanKarmakar** [comment]
> remove the backend folder from the project and make sure the project doesn't give any errors

ha I did that please check the video

**Comment by ArchismanKarmakar** [comment]
> > remove the backend folder from the project and make sure the project doesn't give any errors
> 
> ha I did that please check the video

https://github.com/mohit200008/Gam-Learn/pull/15#issue-1072879915
