### ISSUE TITLE
Redirect to the cards

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#14]
When the user clicks on Stuck anywhere ? Learn with us now button , the user should be redirected to the cards sections where subject cards are shown ??

**Comment by ArchismanKarmakar** [comment]
i want to take up this issue once i've completed previous issues

**Comment by ShivaRapolu01** [comment]
Hello , I have resolved this issue too. I can raise PR for this once my PR for issue #12 gets accepted. So please verify PR for #12. I am ready with the solution for this
