### ISSUE TITLE
Replace the cover photo with a Carousel in the home page 

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#2]
Use photos related to academics.

**Comment by vaibhavjalani** [comment]
@mohit200008 Kindly assign this issue to me

**Comment by mohit200008** [comment]
yeah @vaibhavjalani  go for it

**Comment by riyajha2305** [comment]
can I work on it?

**Comment by mohit200008** [comment]
The issue is already assigned to someone else If the issue isn't fixed by tomorrow You can work on the issue

**Comment by mikrokosmos2109** [comment]
Can you please assign this issue to me?

**Comment by mohit200008** [comment]
Yes @mikrokosmos2109  you can work on it

**Comment by ShivaRapolu01** [comment]
I can work on this @mohit200008 . Please reopen this , I can resolve this

**Comment by mohit200008** [comment]
@ShivaRapolu01  you can work on this
