### ISSUE TITLE
Minor Changes

### ISSUE THREAD

**Issue by ShivaRapolu01** [mohit200008/Gam-Learn#20]
# Spelling mistake:
The spelling "alaways" should be changes to "always"
![image](https://user-images.githubusercontent.com/79957651/145189728-37f54df8-8268-4a64-8d9e-18d86f2c1f16.png)

# Overflow issue : 
The content in maths card is being overflowed when hovered
![image](https://user-images.githubusercontent.com/79957651/145189938-f610ad20-2e41-4c83-a475-1d31941eb6b4.png)

**Comment by mohit200008** [comment]
okay @ShivaRapolu01 you can work on this issue

**Comment by ShivaRapolu01** [comment]
Yeah sure!
