### ISSUE TITLE
Get Questions from the database

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#22]
The questions and options must be called from the database instead of being called locally. The database will store the questions and and array of options for each question.

**Comment by shmiitg** [comment]
I want to take this issue. Please assign me

**Comment by shmiitg** [comment]
For this do we need to create separate databases for each subject or only one?
![Screenshot (274)](https://user-images.githubusercontent.com/70333141/145414022-9791633f-00d9-4968-ad94-de75841e101a.png)
I tested by adding two question for chemistry and the code works fine.

**Comment by shmiitg** [comment]
Shall i add all the questions to the database? I will create separate databases for different subjects

**Comment by mohit200008** [comment]
go ahead @shmiitg

**Comment by shmiitg** [comment]
I have sent a pr, please check
