### ISSUE TITLE
Redesign the cards 

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#3]
Add new card animations  to the subject cards.

**Comment by jakhar434** [comment]
Hello @mohit200008 ,I would like to work on this issue.

**Comment by jakhar434** [comment]
@mohit200008 , kindly assign this issue to me.

**Comment by mohit200008** [comment]
Sure go ahead @jakhar434

**Comment by riyajha2305** [comment]
Can I work on it?

**Comment by jakhar434** [comment]
![Screenshot (1051)](https://user-images.githubusercontent.com/76389609/144746266-684034be-660b-406c-8051-90e92f77aa98.png)
![Screenshot (1050)](https://user-images.githubusercontent.com/76389609/144746281-9a18d6d7-c7ec-487b-bedf-851c372008ca.png)

**Comment by ShivaRapolu01** [comment]
I have redesigned the cards , waiting for my previous PR to get merged @mohit200008 so that I can raise PR for this

**Comment by jakhar434** [comment]
Hello @mohit200008 , why my name is not in the leaderboard, as my PR is merged .

**Comment by ShivaRapolu01** [comment]
@mohit200008  points for this have not been added yet , please add the points to the leaderboard
