### ISSUE TITLE
Adding pull request, issue , bug  templates

### ISSUE THREAD

**Issue by ShivaRapolu01** [mohit200008/Gam-Learn#32]
I feel that adding a pull request and issue template will make this repository more structured and will help beginner to get started.

**Comment by ArchismanKarmakar** [comment]
> I feel that adding a pull request and issue template will make this repository more structured and will help beginner to get started.

i have PR template and issue template ready should i create a PR?

**Comment by re4lvanshsingh** [comment]
Im a beginner could i work on this?

**Comment by ArchismanKarmakar** [comment]
> I feel that adding a pull request and issue template will make this repository more structured and will help beginner to get started.

#34

**Comment by ShivaRapolu01** [comment]
I was waiting for @mohit200008 to consider this as an issue. I would like to work on this @mohit200008 if this issue is considered important now and part of the Gam-learn .

**Comment by ArchismanKarmakar** [comment]
> I was waiting for @mohit200008 to consider this as an issue. I would like to work on this @mohit200008 if this issue is considered important now and part of the Gam-learn .

@ShivaRapolu01 i already created a PR

**Comment by ShivaRapolu01** [comment]
@mohit200008 bhaiya points for pointing out this issue were not awarded. Please update so that I can close this issue

**Comment by ShivaRapolu01** [comment]
@mohit200008  ok leave this issue , what about issue #49 . Will points be awarded for solving that issue. Please reply so that I can stop reminding thinking that points should be awarded  for issue #49

**Comment by mohit200008** [comment]
i gave you points for issue #49

**Comment by mohit200008** [comment]
You will get points for pointing out this

**Comment by ShivaRapolu01** [comment]
Thanks a lot bhaiya 😄
