### ISSUE TITLE
Form for adding more questions  in a particular subjects

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#36]
Create a form for adding new questions  to the database . It should have question, 3 options and chose subject option. Only frontend has to be created for now.

**Comment by ShivaRapolu01** [comment]
I want to work ok this

**Comment by ShivaRapolu01** [comment]
Should I create a new file for this?
should the form consist of only one question?

**Comment by mohit200008** [comment]
Thr form will be having a question and options fields and A plus button to add more than one question.

**Comment by mohit200008** [comment]
Are the questions added by user, also gets added to the database ???

**Comment by ShivaRapolu01** [comment]
No bhaiya , only front-end is created

**Comment by ShivaRapolu01** [comment]
I can try that under another issue

**Comment by ShivaRapolu01** [comment]
Only front-end has to be created right? for this issue

**Comment by mohit200008** [comment]
okay , add a button somewhere so that i can open the form and test it

**Comment by ShivaRapolu01** [comment]
I have added a  button in  navbar named **Add question** of index.html in the English version ,please verify it
