### ISSUE TITLE
Create a suitable About section above the subject cards.

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#4]
Refer to readme for  the content and link the Get Started button to it.

**Comment by ArchismanKarmakar** [comment]
I am doing this sir, please assign this to me. 

I have to add it just below the get started section, am I right sir??

**Comment by mohit200008** [comment]
below the cover page

**Comment by mohit200008** [comment]
go ahead take up this issue @ArchismanKarmakar

**Comment by ArchismanKarmakar** [comment]
sir how can i only update the code of about section?? I have made changes in the main html to make it responsive? so how to push the about section only??

**Comment by ArchismanKarmakar** [comment]
Sir I am a beginner. I am just learning GIT. So please guide me how to add my changes.

**Comment by ArchismanKarmakar** [comment]
https://github.com/ArchismanKarmakar/Gam-Learn/blob/main/frontend/LandingPage/index.html

Here is the forked updated index.html. Please check this and guide me what to do next.

**Comment by mohit200008** [comment]
You have to add an About section below the cover image on the Home page(refer the screen shots ). For the content, you can refer to the description from the readme.

**Comment by mohit200008** [comment]
If you have something to ask you can ask on discord code peak channel

**Comment by ArchismanKarmakar** [comment]
> You have to add an About section below the cover image on the Home page(refer the screen shots ). For the content, you can refer to the description from the readme.

https://github.com/ArchismanKarmakar/Gam-Learn/blob/main/frontend/LandingPage/index.html

Yeah sir i did that please check the screenshot 
![1](https://user-images.githubusercontent.com/92569441/144661077-ce3d8100-31d8-4442-8e99-606e51815760.png)
![2](https://user-images.githubusercontent.com/92569441/144661153-e514fb3f-6209-4810-b824-20196acf0f53.png)
![3](https://user-images.githubusercontent.com/92569441/144661159-fefe6cd7-bff0-49e3-8ec8-21c5f7cffdb3.png)

**Comment by ArchismanKarmakar** [comment]
> You have to add an About section below the cover image on the Home page(refer the screen shots ). For the content, you can refer to the description from the readme.

Done sir, I have made a pull request please check.

**Comment by mohit200008** [comment]
For the text , You can take content from the readme and the contact us and why gamlearn should be the footer .

**Comment by mohit200008** [comment]
The map is not needed here , Replace it with a picture and put them in such a way that it goes with the colour scheme of the header .

**Comment by ArchismanKarmakar** [comment]
> 

ok doing sir
