### ISSUE TITLE
Add a button for reset progress

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#41]
There should be a button on the subjects page for each subject to reset the progress to zero and when user clicks on that , The Progress circle goes back to zero.

**Comment by ShivaRapolu01** [comment]
Willing to work on this , once I get freed  from previous issues 😄

**Comment by ShivaRapolu01** [comment]
Waiting for my PR to get merged to start working on this issue

**Comment by ArchismanKarmakar** [comment]
> There should be a button on the subjects page for each subject to reset the progress to zero and when user clicks on that , The Progress circle goes back to zero.

i want to work please assign me

**Comment by mohit200008** [comment]
go ahead @ArchismanKarmakar

**Comment by ArchismanKarmakar** [comment]
> There should be a button on the subjects page for each subject to reset the progress to zero and when user clicks on that , The Progress circle goes back to zero.

#44

**Comment by mohit200008** [comment]
@ArchismanKarmakar  the reset button and everything is gone. Please add that feature
