### ISSUE TITLE
on login the page should be redirected to home page not subjects page

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#47]
When user log in , the home page having the carousel should appear not the subjects page.

**Comment by ShivaRapolu01** [comment]
Just found this issue

**Comment by ShivaRapolu01** [comment]
Can I raise a PR for both issues?

**Comment by ShivaRapolu01** [comment]
Will work on this simultaneously

**Comment by ShivaRapolu01** [comment]
The index.html under LandingPage is  changed

**Comment by ShivaRapolu01** [comment]
@mohit200008  I fixed this. Please merge my present PR so that I can raise PR for this issue

**Comment by ShivaRapolu01** [comment]
@mohit200008 please update the leaderboard with the points of solving this issue.
