### ISSUE TITLE
Make the site responsive on all screen sizes.

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#5]
Currently the site is suitable for desktop screen only. Make it responsive for all standard screen sizes.

**Comment by zayed-shamshad** [comment]
hey @mohit200008  I can take up this issue ,kindly assign it to me.

**Comment by mohit200008** [comment]
yeah @zayed-shamshad  go-ahead

**Comment by riyajha2305** [comment]
Can I work on this issue?

**Comment by mohit200008** [comment]
The issue is already assigned you can look or create some other issue

**Comment by Code-Aditya-14** [comment]
Hey @mohit200008, can I work on this issue.

**Comment by mohit200008** [comment]
Sure @Code-Aditya-14  go ahead. But the site is going through some changes so make sure to work according to that.

**Comment by ShivaRapolu01** [comment]
@mohit200008  I can make the navbar responsive under a new separate issue. Can I open a separate issue for navbar?

**Comment by ShivaRapolu01** [comment]
@mohit200008  I would like to work on this whole issue

**Comment by mohit200008** [comment]
Go ahead @ShivaRapolu01

**Comment by ShivaRapolu01** [comment]
Can you Please make this hard , since you can see many have claimed this but didn't submit , so i think much effort has to be put into this

**Comment by mohit200008** [comment]
Go ahead @ShivaRapolu01
