### ISSUE TITLE
Reset progress feature when user is viewing subjects page in English

### ISSUE THREAD

**Issue by ShivaRapolu01** [mohit200008/Gam-Learn#50]
# Description
There is no reset progress button available in English subject page as in the case of Hindi subject page

#files to work on 
frontend/LandingPage/stud-sc.html

# Screenshot
![image](https://user-images.githubusercontent.com/79957651/146385154-51563fc6-6214-4937-8f0f-13b65132865f.png)

**Comment by ShivaRapolu01** [comment]
I would like to work on this

**Comment by ShivaRapolu01** [comment]
@mohit200008  bhaiya can i work on this?

**Comment by mohit200008** [comment]
go ahead @ShivaRapolu01  but it should be like what @ArchismanKarmakar  did
