### ISSUE TITLE
Add a new page for displaying the scores of students

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#51]
Add a new page for displaying the scores of students and immediately when the game ends it should be redirected to the scores page. ALso there should be a link on navbar for the scores page.

**Comment by ShivaRapolu01** [comment]
Only a page should be created or have to design the content inside the page also?

**Comment by mohit200008** [comment]
design also

**Comment by ShivaRapolu01** [comment]
I am willing to work on this
