### ISSUE TITLE
Add a chatbot on the right bottom of the website

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#52]
https://lucasbassetti.com.br/react-simple-chatbot/
This can be used for adding the chatbot and any other alternative is also allowed

**Comment by ShivaRapolu01** [comment]
I must run create-react-app to install this right?

**Comment by mohit200008** [comment]
its an example that i showed , you can use any library that you want

**Comment by shmiitg** [comment]
is there any chatbot library available for js? I couldn't find any
