### ISSUE TITLE
Add a link on navbar for scores

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#56]
Add a link on navbar for showing the scores of students. After the game ends the user redirects to the scores page.

**Comment by Pranav108** [comment]
Can I take it?

**Comment by mohit200008** [comment]
@Pranav108  sure go ahead

**Comment by ShivaRapolu01** [comment]
pranav108 has unassigned himself , can I work on this simultaneously with #51

**Comment by mohit200008** [comment]
You have to first complete #51  issue

**Comment by shmiitg** [comment]
I created a pr for #65, can I get this issue?

**Comment by mohit200008** [comment]
yes go ahead @shmiitg
