### ISSUE TITLE
Create a page to display the scores of students.

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#6]
Also make a section for average score. Make sure it follows the color scheme of the Home page.

**Comment by ArchismanKarmakar** [comment]
I want to take up this. Please assign me in this.

**Comment by ArchismanKarmakar** [comment]
I want to take up this issue please assign me

**Comment by mohit200008** [comment]
One person can have one issue at a time.

**Comment by mohit200008** [comment]
Yes @ArchismanKarmakar  you can take up this issue

**Comment by ArchismanKarmakar** [comment]
> Yes @ArchismanKarmakar you can take up this issue



> Yes @ArchismanKarmakar you can take up this issue

working

**Comment by ArchismanKarmakar** [comment]
> Yes @ArchismanKarmakar you can take up this issue

now check sir #23

**Comment by mohit200008** [comment]
@ArchismanKarmakar  where is the link to open the score page ?????

**Comment by ArchismanKarmakar** [comment]
okay i am adding a button in home page, i forgot that one

**Comment by mohit200008** [comment]
The css for the subject page is not there

**Comment by ArchismanKarmakar** [comment]
> The css for the subject page is not there

i corrected that already you can check the uploaded files

**Comment by ArchismanKarmakar** [comment]
> The css for the subject page is not there

https://github.com/mohit200008/Gam-Learn/pull/25/commits/4352b2e4b42a796d4542c65d8ca35fb9ca1d9d78

sir please check the location, i uploaded the CSS

**Comment by mohit200008** [comment]
![Capture](https://user-images.githubusercontent.com/56565813/145270451-dd9f31ba-1e46-46d3-8532-4b1d29dca563.PNG)

**Comment by mohit200008** [comment]
Something's wrong

**Comment by ArchismanKarmakar** [comment]
> Something's wrong

#26 check now sir i corrected everything. you must have accepted other PRs so my fork did'nt update. that caused the issue

**Comment by mohit200008** [comment]
Okay @ArchismanKarmakar  points have rewarded to you for you work

**Comment by ArchismanKarmakar** [comment]
> Okay @ArchismanKarmakar  points have rewarded to you for you work 

Thanks Bhaiya
