### ISSUE TITLE
Reset button on student score page shows the href link on hover

### ISSUE THREAD

**Issue by shmiitg** [mohit200008/Gam-Learn#62]
# Description
On hovering over the reset button, it shows the href link which gives the impression that it is going to navigate the user to some other route which is not good for user experience. On hovering over the card, this behaviour is fine but on hovering over the reset button this shouldn't be there

# Relevant files
stud-sc.html

# Screenshot
![Screenshot (317)_LI](https://user-images.githubusercontent.com/70333141/147150487-93e1d5ad-a352-4dae-8f5f-4950d5f40b49.jpg)
This link is shown when user hover overs the card which is fine, but while hovering over the reset button this link shouldn't be shown

**Comment by shmiitg** [comment]
If you think this is a genuine issue, I would like to resolve this

**Comment by mohit200008** [comment]
On clicking the reset button, The It shouldn't redirect to another page , it should just reset the circular bar to zero. Can you resolve this issue too ???

**Comment by mohit200008** [comment]
you can go ahead and resolve both these issues @shmiitg  i am assigning you this.

**Comment by shmiitg** [comment]
yaah i will do this

**Comment by ShivaRapolu01** [comment]
Previously I worked on this, it is not redirecting to another page , it is showing just on hover
