### ISSUE TITLE
Logout button on english page doesn't work

### ISSUE THREAD

**Issue by shmiitg** [mohit200008/Gam-Learn#64]
# Description
The logout button doesn't work in the english page and user credentials are also not shown at the top. On clicking, it just simply redirects to the login page and doesn't logout the user.
**This issue was not there when I implemented the auth system but i guess in some previous commits someone changed the code and thats why it doesn't work now

**Comment by shmiitg** [comment]
I would like to correct this

**Comment by shmiitg** [comment]
![Screenshot (323)_LI](https://user-images.githubusercontent.com/70333141/147378116-b8d56b16-5a0e-4375-8d6e-d7a18553814b.jpg)
You can see that the user credential is not shown in english page and also the logout button only redirects to signup page instead of logging out the user

**Comment by shmiitg** [comment]
![Screenshot (324)](https://user-images.githubusercontent.com/70333141/147378132-fdde0948-78c3-4c56-9e5c-36940a605de7.png)
In the hindi page user credential are shown and after logging out the user the logout button changes to login
![Screenshot (325)](https://user-images.githubusercontent.com/70333141/147378142-bd8f6bf1-92b2-4711-a1a7-5f3ee039f1c2.png)

**Comment by ShivaRapolu01** [comment]
@mohit200008 seems like I solved this issue unknowingly. Can you divide the points for solving the issue between @shmiitg and me and update the leaderboard?
