### ISSUE TITLE
redesign the score page 

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#67]
The score page has to be re designed so that it should look more appealing

**Comment by ShivaRapolu01** [comment]
Can I design it as a grade card ?

**Comment by ShivaRapolu01** [comment]
@mohit200008 please have a look at this design ( designed keeping website theme in mind )
https://www.awesomescreenshot.com/video/6590670?key=f001ca1c1f4cd44dec3be502dff0b082
The table is completely responsive and height changes according to the content size

**Comment by ShivaRapolu01** [comment]
The navbar responsiveness would be handled in #5

**Comment by mohit200008** [comment]
good work @ShivaRapolu01

**Comment by ShivaRapolu01** [comment]
Thanks bhaiya
