### ISSUE TITLE
Redirection from one page to another not properly working

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#69]
When subject page is opened some links on navbar dis appeared , And when a link is opened , and when clicking on home link its not redirecting. Resolve the redirections and navigations. The credentials should be shown beside the home page when logged in.

**Comment by ShivaRapolu01** [comment]
I would like to work on This

**Comment by ShivaRapolu01** [comment]
I would like to work on this

**Comment by mohit200008** [comment]
Go ahead @ShivaRapolu01
