### ISSUE TITLE
Use firebase authentication for login/signup

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#7]
. we want this function to implement in such a way that when someone enters his/her credentials,  He/She should be redirected to the home page on signup  and his credentials should be shown on the top also stored on the database.  And validate while logging in and then redirect to home page.

**Comment by riyajha2305** [comment]
Can I work on this issue?

**Comment by mohit200008** [comment]
Yeah sure @riyajha2305  go ahead

**Comment by shmiitg** [comment]
can I work this issue?

**Comment by shmiitg** [comment]
can i work on this?

**Comment by mohit200008** [comment]
Its a hard issue , for hard issue you will get 6 days to complete. After that next person will be assigned

**Comment by shmiitg** [comment]
> Its a hard issue , for hard issue you will get 6 days to complete. After that next person will be assigned

ok

**Comment by shmiitg** [comment]
> The login signup functionality will be done with the help of hooks and context. So we want this function to implement in such a way that when someone enters his/her credentials, He/She should be redirected to the home page and his credentials should be shown on the top.

For using context and hooks we need to shift the project to react instead of html right? I will implement the auth functionality using firebase and react. You can assign this issue to me

**Comment by mohit200008** [comment]
> > The login signup functionality will be done with the help of hooks and context. So we want this function to implement in such a way that when someone enters his/her credentials, He/She should be redirected to the home page and his credentials should be shown on the top.
> 
> For using context and hooks we need to shift the project to react instead of html right? I will implement the auth functionality using firebase and react. You can assign this issue to me

Please don't implement it in react , its a typo mistake from our side

**Comment by riyajha2305** [comment]
> > > The login signup functionality will be done with the help of hooks and context. So we want this function to implement in such a way that when someone enters his/her credentials, He/She should be redirected to the home page and his credentials should be shown on the top.
> > 
> > 
> > For using context and hooks we need to shift the project to react instead of html right? I will implement the auth functionality using firebase and react. You can assign this issue to me
> 
> Please don't implement it in react , its a typo mistake from our side

wasn't this signup sign in to be code in react?? I actually took the step back just because I had coded in js
