### ISSUE TITLE
Redirecting to score page not working from hindi version 

### ISSUE THREAD

**Issue by ShivaRapolu01** [mohit200008/Gam-Learn#71]
# Description
Redirecting to score page not working from hindi version 

# Screenshot
[Problem Illustration](https://www.awesomescreenshot.com/video/6599088?key=03be1396dd15cb7ba1c2b361890b74bd)

**Comment by ShivaRapolu01** [comment]
I would like to work on this

**Comment by ShivaRapolu01** [comment]
Problem video https://www.awesomescreenshot.com/video/6599088?key=03be1396dd15cb7ba1c2b361890b74bd

**Comment by ShivaRapolu01** [comment]
About this ?

**Comment by ShivaRapolu01** [comment]
@mohit200008  about this ?

**Comment by mohit200008** [comment]
Go ahead

**Comment by mohit200008** [comment]
you can work on this issue

**Comment by ShivaRapolu01** [comment]
Ok bhaiya
