### ISSUE TITLE
10 cards are being shown instead of 5 in Hindi version

### ISSUE THREAD

**Issue by ShivaRapolu01** [mohit200008/Gam-Learn#72]
# Description
10 cards are being shown instead of 5 in Hindi version

# Screenshot
![image](https://user-images.githubusercontent.com/79957651/147415782-747a5e6f-a265-4b4b-8133-ce06c1a5d3a4.png)

**Comment by ShivaRapolu01** [comment]
I want to solve this issue

**Comment by mohit200008** [comment]
@ShivaRapolu01  go ahead
