### ISSUE TITLE
Cards not looking appealing in dark mode

### ISSUE THREAD

**Issue by ShivaRapolu01** [mohit200008/Gam-Learn#78]
# Description
Cards not looking appealing in dark mode

# Screenshot
![image](https://user-images.githubusercontent.com/79957651/147542160-8edef1f9-8be0-40b2-a683-6eb90a74d1e2.png)

**Comment by ShivaRapolu01** [comment]
@mohit200008 I would like to redesign the color contrast of the cards so that they look appealing in dark mode

**Comment by ShivaRapolu01** [comment]
@mohit200008  can I work on this ?

**Comment by ShivaRapolu01** [comment]
My intention was to provide white background and black color text to the cards . If not required I can close this issue @mohit200008

**Comment by mohit200008** [comment]
Its looking good as per dark mode
