### ISSUE TITLE
Deleting unwanted folders and files

### ISSUE THREAD

**Issue by shmiitg** [mohit200008/Gam-Learn#82]
# Description
Some unwanted folders and files have been created in previous commits

# Screenshot
![Screenshot (356)_LI](https://user-images.githubusercontent.com/70333141/147669449-29330445-cec2-48d3-8ecc-0a6cc8ce5b53.jpg)

**Comment by shmiitg** [comment]
I would like to remove them once you approve this issue

**Comment by mohit200008** [comment]
Make sure the project works as before without any errors.

**Comment by shmiitg** [comment]
ok
