### ISSUE TITLE
Dark mode toggle button becomes a bit off when size of screen is reduced

### ISSUE THREAD

**Issue by shmiitg** [mohit200008/Gam-Learn#85]
# Description
The dark mode toggle button seems to go off when the screen size reduces (this only occurs when the user is logged in because it takes up some extra space), but it works fine for non logged users

https://user-images.githubusercontent.com/70333141/147757980-96ec4fd9-a440-45b4-a998-42cebbde3d98.mp4

**Comment by shmiitg** [comment]
I would like to correct this once you approve the issue

**Comment by mohit200008** [comment]
Go ahead @shmiitg
