### ISSUE TITLE
Missing user dashboard

### ISSUE THREAD

**Issue by shmiitg** [mohit200008/Gam-Learn#87]
# Description
When the user clicks on the credentials, it should open the dashboard. In the dashboard, we can show all the test scores the user has attended by fetching them from the database or we can redirect to the student progress page instead of showing the test scores, whatever you say

**Comment by shmiitg** [comment]
I would like to work on this once you approve this

**Comment by shmiitg** [comment]
Or we can redirect to the student progress page instead of showing the test scores, whatever you say

**Comment by mohit200008** [comment]
Go ahead @shmiitg, you can work on this
