### ISSUE TITLE
Connect to the Firebase database to store the student scores.

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/Gam-Learn#9]
Connect a firebase database to store the student names and their respective scores.

**Comment by shmiitg** [comment]
I would like to work on this issue

**Comment by mohit200008** [comment]
Here whatever the student scores in the game , his/her scores should be displayed on a seperate page.

**Comment by mohit200008** [comment]
I am sure you understood @shmiitg  and also the cards on subjects page are not linked to the questions page

**Comment by mohit200008** [comment]
You can work on this @shmiitg

**Comment by shmiitg** [comment]
The score page looks like this
![Screenshot (307)](https://user-images.githubusercontent.com/70333141/146172176-307cf06a-c238-4e09-971b-690510fb95ef.png)
After the game gets over, the user will be redirected to this page where they can see their last quiz scores of all subjects and their scores will be stored in the database as follows:
![Screenshot (308)](https://user-images.githubusercontent.com/70333141/146172404-8ccf696c-221f-4349-b18e-245fad61645f.png)
If you want any changes please tell or else I will make a pr and you can review that
