### ISSUE TITLE
While adding a question in question form its cloning the first question

### ISSUE THREAD

**Issue by shmiitg** [mohit200008/Gam-Learn#95]
# Description
When add question option is clicked, it is cloning the first question while it should make a blank form for adding question

https://user-images.githubusercontent.com/70333141/148388549-499e7b1b-b7c1-42d5-824e-cb4b25fe758a.mp4

You can see that the exact question is copied instead of opening a blank form

**Comment by shmiitg** [comment]
I am working on it

**Comment by mohit200008** [comment]
Yes @shmiitg  go ahead

**Comment by shmiitg** [comment]
I have linked a pr for this. You can review that. That fixes both #95 and #93
